import java.text.SimpleDateFormat

plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "io.freefair.lombok" version "8.11"
	id "com.modrinth.minotaur" version "2.8.7"
}

version = 'git rev-parse --short HEAD'.execute().text.trim()
group = project.maven_group

repositories {
	mavenCentral()

	maven { url "https://maven.terraformersmc.com/releases/" }
	maven { url "https://maven.shedaniel.me/" }
	maven { url "https://maven.projecteden.gg/repo" }
	maven { url "https://repo.eclipse.org/content/groups/releases/" }
	maven { url "https://jitpack.io" }
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	implementation include("net.lingala.zip4j:zip4j:2.11.1") {
		transitive(true)
	}

	implementation include("org.eclipse.jgit:org.eclipse.jgit:6.5.0.202303070854-r") {
		transitive(true)
	}

	modImplementation ("com.terraformersmc:modmenu:${project.modmenu_version}") {
		exclude (group: "net.fabricmc.fabric-api")
	}

	modImplementation include ("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}") {
		exclude (group: "net.fabricmc.fabric-api")
	}

	implementation include("com.github.JnCrMx:discord-game-sdk4j:v0.5.5")

	implementation include("org.apache.httpcomponents.client5:httpclient5:5.5.1")
	implementation include("org.apache.httpcomponents.core5:httpcore5:5.3")
	implementation include("org.apache.httpcomponents.core5:httpcore5-h2:5.3")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	// ensure that the encoding is set to UTF-8, no matter what the system default is
	// this fixes some edge cases with special characters not displaying correctly
	// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	// If Javadoc is generated, this must be specified in that task too.
	it.options.encoding = "UTF-8"

	// Minecraft 1.18 (1.18-pre2) upwards uses Java 17.
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}

	manifest {
		attributes(
			'Build-Timestamp': new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS").format(new Date())
		)
	}
}

remapJar {
	// Set the final name of the jar! This needs to be exactly this for the auto-update function to work!
	archiveFileName = "titan.jar"
}

modrinth {
	token = System.getenv("MODRINTH_TOKEN")
	projectId = "f44hEoWP"
	versionNumber = project.version
	uploadFile = jar
	gameVersions = ["${minecraft_version}"]
	loaders = ["fabric"]
	uploadFile = "./build/libs/titan.jar"
	dependencies {
		required.project "fabric-api"
		required.project "cloth-config"
		required.project "modmenu"
	}
}
